export const  INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"
export const COUNTER_ACTION_START = "COUNTER_ACTION_START"
export const COUNTER_ACTION_FINISHED ="COUNTER_ACTION_FINISHED"